### ISSUE TITLE
Parsing with StreamingParser fails with file 86kb

### ISSUE THREAD

**Issue by Pato05** [amphp/http-server-form-parser#8]
I have a form which contains an input file. If I put an image of ~86kb it produces many PHP warning of strpos "Offset not contained in string" and fails with error 500, because it throws "Request body ended unexpectedly".
Using MadelineProto too with Amp.
[log.txt](https://github.com/amphp/http-server-form-parser/files/4375562/log_amphp.txt)

**Comment by Pato05** [comment]
About the increasing of the size limit? Maybe adding a method to do so?

**Comment by trowski** [comment]
@Pato05 You can use `RequestBody::increaseSizeLimit($newSizeLimit)`.

**Comment by kelunik** [comment]
There's already a method for that: `$request->getBody()->increaseSizeLimit(...)`. I've added an example to show how it works:

https://github.com/amphp/http-server-form-parser/blob/657d945ebc4d5a3b1ea7b1d25c52fb2fdb118f1d/examples/streaming-form.php#L44-L61

**Comment by Pato05** [comment]
Oh ok, so just call $request->getBody(). Thanks guys!
